# Generated by Django 4.2.11 on 2026-05-28 09:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='仪器名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='仪器编号')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='型号')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='生产厂商')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='放置位置')),
                ('status', models.CharField(choices=[('available', '可用'), ('in_use', '使用中'), ('maintenance', '维护中'), ('unavailable', '不可用')], default='available', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('specifications', models.TextField(blank=True, verbose_name='技术规格')),
                ('image', models.CharField(blank=True, max_length=255, verbose_name='仪器图片')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='需要审批')),
                ('daily_max_hours', models.IntegerField(default=8, verbose_name='每日最长使用时长(小时)')),
                ('reservation_lead_days', models.IntegerField(default=14, verbose_name='可提前预约天数')),
                ('min_reservation_hours', models.FloatField(default=0.5, verbose_name='最小预约时长(小时)')),
                ('max_reservation_hours', models.FloatField(default=8, verbose_name='最大预约时长(小时)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '仪器',
                'verbose_name_plural': '仪器',
                'db_table': 'instruments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='分类编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '仪器分类',
                'verbose_name_plural': '仪器分类',
                'db_table': 'instrument_categories',
            },
        ),
        migrations.CreateModel(
            name='InstrumentMaintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('routine', '例行维护'), ('repair', '故障维修'), ('calibration', '校准'), ('upgrade', '升级')], max_length=20, verbose_name='维护类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('scheduled_date', models.DateField(verbose_name='计划日期')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='实际日期')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='操作人员')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='费用')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='instruments.instrument')),
            ],
            options={
                'verbose_name': '仪器维护',
                'verbose_name_plural': '仪器维护',
                'db_table': 'instrument_maintenances',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.AddField(
            model_name='instrument',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments', to='instruments.instrumentcategory'),
        ),
    ]
