listener 1883
listener 9001
protocol websockets

allow_anonymous true
connection_messages true
log_type all

persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log

max_queued_messages 1000
message_size_limit 10485760
