apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://localhost:8123
    user: default
    secureJsonData:
      password: ""
    jsonData:
      defaultDatabase: industrial_iot
      server: localhost
      port: 8123
      protocol: http
      username: default
      tlsSkipVerify: true
    editable: true
