# Generated by Django 4.2.11 on 2026-05-28 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0001_initial'),
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('experiment_content', models.TextField(blank=True, verbose_name='实验内容')),
                ('sample_info', models.TextField(blank=True, verbose_name='样品信息')),
                ('result_summary', models.TextField(blank=True, verbose_name='结果摘要')),
                ('anomalies', models.TextField(blank=True, verbose_name='异常情况')),
                ('usage_duration', models.FloatField(default=0, verbose_name='使用时长(小时)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_records', to='instruments.instrument')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='use_records', to='reservations.reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '使用记录',
                'verbose_name_plural': '使用记录',
                'db_table': 'use_records',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['instrument_id'], name='use_records_instrum_a3f003_idx'), models.Index(fields=['user_id'], name='use_records_user_id_2be5b0_idx'), models.Index(fields=['start_time'], name='use_records_start_t_920067_idx')],
            },
        ),
    ]
