# Generated by Django 4.2.11 on 2026-05-28 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('violation_type', models.CharField(choices=[('late_cancel', '超时取消'), ('no_show', '未到场'), ('equipment_damage', '设备损坏'), ('rule_violation', '违规操作'), ('unauthorized_use', '未授权使用'), ('other', '其他')], max_length=20, verbose_name='违规类型')),
                ('severity', models.CharField(choices=[('minor', '轻微'), ('moderate', '一般'), ('major', '严重'), ('critical', '极严重')], max_length=10, verbose_name='严重程度')),
                ('description', models.TextField(verbose_name='违规描述')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('confirmed', '已确认'), ('appealed', '已申诉'), ('dismissed', '已驳回'), ('resolved', '已处理')], default='pending', max_length=10, verbose_name='处理状态')),
                ('penalty', models.CharField(blank=True, choices=[('warning', '警告'), ('suspend_1d', '停用1天'), ('suspend_3d', '停用3天'), ('suspend_7d', '停用7天'), ('suspend_30d', '停用30天'), ('ban', '永久禁止')], max_length=15, verbose_name='处罚措施')),
                ('appeal_reason', models.TextField(blank=True, verbose_name='申诉理由')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='instruments.instrument')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_violations', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_violations', to=settings.AUTH_USER_MODEL)),
                ('use_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='records.userecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '违规使用标记',
                'verbose_name_plural': '违规使用标记',
                'db_table': 'violation_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['instrument_id'], name='violation_r_instrum_47b526_idx'), models.Index(fields=['user_id'], name='violation_r_user_id_a48b86_idx'), models.Index(fields=['status'], name='violation_r_status_08c53f_idx')],
            },
        ),
        migrations.CreateModel(
            name='InstrumentEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(verbose_name='评分')),
                ('content', models.TextField(blank=True, verbose_name='评价内容')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='评价标签')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='instruments.instrument')),
                ('use_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='records.userecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '仪器使用评价',
                'verbose_name_plural': '仪器使用评价',
                'db_table': 'instrument_evaluations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['instrument_id'], name='instrument__instrum_1b966d_idx'), models.Index(fields=['user_id'], name='instrument__user_id_fb7b74_idx')],
            },
        ),
    ]
