# Generated by Django 4.2.11 on 2026-05-28 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('login', '登录'), ('logout', '登出'), ('approve', '审核'), ('reject', '拒绝'), ('cancel', '取消'), ('download', '下载'), ('upload', '上传'), ('view', '查看'), ('export', '导出'), ('import', '导入'), ('other', '其他')], default='other', max_length=20, verbose_name='操作类型')),
                ('module', models.CharField(choices=[('accounts', '用户管理'), ('instruments', '仪器管理'), ('reservations', '预约管理'), ('records', '使用记录'), ('files', '文件管理'), ('notifications', '消息通知'), ('audit', '审计日志'), ('system', '系统设置'), ('other', '其他')], default='other', max_length=20, verbose_name='所属模块')),
                ('resource_type', models.CharField(blank=True, max_length=100, verbose_name='资源类型')),
                ('resource_id', models.UUIDField(blank=True, null=True, verbose_name='资源ID')),
                ('detail', models.TextField(blank=True, verbose_name='操作详情')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='旧值')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='新值')),
                ('ip_address', models.CharField(blank=True, max_length=50, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='audit_logs_user_id_73c422_idx'), models.Index(fields=['action'], name='audit_logs_action_31f574_idx'), models.Index(fields=['module'], name='audit_logs_module_f52b4d_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_logs_resourc_bda8a6_idx'), models.Index(fields=['created_at'], name='audit_logs_created_262184_idx')],
            },
        ),
    ]
