FROM openjdk:8-jre-alpine

LABEL maintainer="iot-gateway"

WORKDIR /app

COPY iot-gateway-api/target/iot-gateway-api-1.0.0.jar app.jar

EXPOSE 8081 502 8080 9090

ENV JVM_OPTS="-Xms512m -Xmx1024m"

ENTRYPOINT ["sh", "-c", "java $JVM_OPTS -Djava.security.egd=file:/dev/./urandom -jar app.jar"]
