# Generated by Django 4.2.11 on 2026-05-28 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0001_initial'),
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='文件名称')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=100, verbose_name='MIME类型')),
                ('size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('category', models.CharField(choices=[('image', '图片'), ('document', '文档'), ('video', '视频'), ('audio', '音频'), ('archive', '压缩包'), ('other', '其他')], default='other', max_length=20, verbose_name='文件分类')),
                ('storage_key', models.CharField(max_length=500, verbose_name='存储键')),
                ('bucket', models.CharField(max_length=100, verbose_name='存储桶')),
                ('etag', models.CharField(blank=True, max_length=100, verbose_name='ETag')),
                ('current_version', models.IntegerField(default=1, verbose_name='当前版本')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='标签')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载次数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='instruments.instrument')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
                ('use_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='records.userecord')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
                'db_table': 'files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileDownloadLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(blank=True, max_length=50, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='下载时间')),
                ('downloaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='files.file')),
            ],
            options={
                'verbose_name': '文件下载日志',
                'verbose_name_plural': '文件下载日志',
                'db_table': 'file_download_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(verbose_name='版本号')),
                ('name', models.CharField(max_length=255, verbose_name='文件名称')),
                ('size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('storage_key', models.CharField(max_length=500, verbose_name='存储键')),
                ('etag', models.CharField(blank=True, max_length=100, verbose_name='ETag')),
                ('change_log', models.TextField(blank=True, verbose_name='变更说明')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='files.file')),
            ],
            options={
                'verbose_name': '文件版本',
                'verbose_name_plural': '文件版本',
                'db_table': 'file_versions',
                'ordering': ['-version'],
                'unique_together': {('file', 'version')},
            },
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['uploaded_by'], name='files_uploade_eeab7f_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['instrument'], name='files_instrum_d042f9_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['use_record'], name='files_use_rec_8a41d3_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['category'], name='files_categor_8c8f96_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['storage_key'], name='files_storage_0bb572_idx'),
        ),
    ]
